packages:
  - apps/*
  - packages/*
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.8b23a00f98df4a9270ac87a4f80b2ce1b669040b
  vite-plus: 0.0.0-commit.8b23a00f98df4a9270ac87a4f80b2ce1b669040b
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
  '@voidzero-dev/vite-plus-core': 0.2.2
  '@types/react': 19.2.15
  '@types/react-dom': 19.2.3
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
    '@types/react': 19.2.15
    '@types/react-dom': 19.2.3
